  
  steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/timeoff-management:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gl-test-339218/docker-repo/timeoff-management:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cloud-run-continuous-deployment', '--image=gcr.io/gl-test-339218/docker-repo/timeoff-management:$SHORT_SHA', '--region=us-east1']
