  steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/gl-test-339218/timeoff:$COMMIT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/gl-test-339218/timeoff:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "timeoff"
      - "--image"
      - "gcr.io/gl-test-339218/timeoff:$COMMIT_SHA"
      - "--region"
      - "us-east1"
  images:
  - "gcr.io/gl-test-339218/timeoff:$COMMIT_SHA"
